name: Deploy Quartz site to GitHub Pages
 
on:
  workflow_dispatch:
  schedule:
    - cron: "45 */1 * * *"
  push:
    branches:
      - v4
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  update:
    if: ${{ "$(echo github.repository)" == 'quartz-themes-preview-template' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - name: Update Quartz
        run: |
          git config pull.rebase >&- || git config pull.rebase false
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config remote.upstream.url >&- || git remote add upstream https://github.com/jackyzha0/quartz.git
          git pull upstream v4 --allow-unrelated-histories
      - name: Push updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          skip_fetch: true
          skip_dirty_check: false
          commit_message: "[ci] quartz: auto-updated"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
  build:
    if: $(echo ${{ github.repository }} != quartz-themes-preview-template)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Update Quartz
        run: |
          git config pull.rebase >&- || git config pull.rebase false
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config remote.template.url >&- || git remote add template https://github.com/quartz-themes/quartz-themes-preview-template.git
          git pull template v4 --allow-unrelated-histories
      - name: Push updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          skip_fetch: true
          skip_dirty_check: false
          commit_message: "[ci] quartz-themes: auto-updated"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
      - name: Install Dependencies
        run: npm ci
      - name: Fetch Quartz Theme
        run: curl -s -S https://raw.githubusercontent.com/saberzero1/quartz-themes/master/action.sh | bash -s -- ${{ github.event.repository.name }}
      - name: Build Quartz Docs
        run: npx quartz build -d docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
